version: '3.8'

services:
#  app:
#    build:
#      context: .
#    ports:
#      - "3000:3000"
#    depends_on:
#      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: